### ISSUE TITLE
[EKS] Migrate to Blueprint v5

### ISSUE THREAD

**Issue by carlosrodlop** [carlosrodlop/terraform-lib#10]
Using [eks_addons](https://github.com/carlosrodlop/terraform-lib/blob/959accf61146155a080f1af4dd6cf346b6b35158/clouds/aws/modules/aws-eks-addons-v5/main.tf#L41-L45) `terraform apply` fails with 

```
│ Error: reading EKS Add-On version info (aws-ebs-csi-driver, oidc.eks.us-east-1.amazonaws.com/id/E1C911A3EDCB4646E262BA6AA11D07F5): Empty result
│
│   with module.aws-eks-addons-v5[0].module.eks_blueprints_addons.data.aws_eks_addon_version.this["aws-ebs-csi-driver"],
│   on .terraform/modules/aws-eks-addons-v5.eks_blueprints_addons/main.tf line 2171, in data "aws_eks_addon_version" "this":
│ 2171: data "aws_eks_addon_version" "this" {
│
╵
╷
│ Error: reading EKS Add-On version info (coredns, oidc.eks.us-east-1.amazonaws.com/id/E1C911A3EDCB4646E262BA6AA11D07F5): Empty result
│
│   with module.aws-eks-addons-v5[0].module.eks_blueprints_addons.data.aws_eks_addon_version.this["coredns"],
│   on .terraform/modules/aws-eks-addons-v5.eks_blueprints_addons/main.tf line 2171, in data "aws_eks_addon_version" "this":
│ 2171: data "aws_eks_addon_version" "this" {
│
╵
╷
│ Error: reading EKS Add-On version info (vpc-cni, oidc.eks.us-east-1.amazonaws.com/id/E1C911A3EDCB4646E262BA6AA11D07F5): Empty result
│
│   with module.aws-eks-addons-v5[0].module.eks_blueprints_addons.data.aws_eks_addon_version.this["vpc-cni"],
│   on .terraform/modules/aws-eks-addons-v5.eks_blueprints_addons/main.tf line 2171, in data "aws_eks_addon_version" "this":
│ 2171: data "aws_eks_addon_version" "this" {
│
╵
╷
│ Error: reading EKS Add-On version info (kube-proxy, oidc.eks.us-east-1.amazonaws.com/id/E1C911A3EDCB4646E262BA6AA11D07F5): Empty result
│
│   with module.aws-eks-addons-v5[0].module.eks_blueprints_addons.data.aws_eks_addon_version.this["kube-proxy"],
│   on .terraform/modules/aws-eks-addons-v5.eks_blueprints_addons/main.tf line 2171, in data "aws_eks_addon_version" "this":
│ 2171: data "aws_eks_addon_version" "this" {
```

Removing [eks_addons](https://github.com/carlosrodlop/terraform-lib/blob/959accf61146155a080f1af4dd6cf346b6b35158/clouds/aws/modules/aws-eks-addons-v5/main.tf#L41-L45)  make `terraform apply` finish successfully.

Expectation: Fully implement this pattern in v5 https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/v5.0.0/examples/stateful

Things to validate:
* Current EKS cluster version is [1.25](https://github.com/carlosrodlop/terraform-lib/blob/959accf61146155a080f1af4dd6cf346b6b35158/clouds/aws/root/01_infra/variables.tf#L43) but v5 is using [1.27 ](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v5.0.0/examples/stateful/main.tf#L62)
* Align required providers to https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v5.0.0/examples/stateful/versions.tf#L4-L21

**Comment by wellsiau-aws** [comment]
@carlosrodlop , this is caused by the [invalid variable assignment in here](https://github.com/carlosrodlop/terraform-lib/blob/main/clouds/aws/modules/aws-eks-addons-v5/main.tf#L37-L38).

```
cluster_version   = var.eks_oidc_provider
oidc_provider_arn = var.eks_cluster_version
```

**Comment by carlosrodlop** [comment]
@wellsiau-aws thanks., Issue solved!
